#!/usr/bin/env bash
# Xbox queue bursts (tc police) + optional NIC ring buffers on the gaming path.
# Xbox-only: ingress police burst applies only to XBOX_IP/MAC filters.
# NIC rings are path-wide (LAN bridge) but reduce drops for Xbox UDP bursts.
set -euo pipefail

TOOLS_DIR="/home/pi/gaming-tools"
CONF="${TOOLS_DIR}/gaming.conf"
STATE="${TOOLS_DIR}/.buffer-tune.state"
RING_STATE="${TOOLS_DIR}/.buffer-tune.rings.json"
ENV_FILE="${TOOLS_DIR}/.xbox-buffer.env"
PHYS_IFACES="${BUFFER_PHYS_IFACES:-eth0 eth1 eth2}"

if [[ -f "$CONF" ]]; then
  # shellcheck disable=SC1090
  source "$CONF"
fi
# shellcheck disable=SC1091
source "${TOOLS_DIR}/xbox-scope.sh"

log() { printf '[buffer-tune] %s\n' "$*"; }

need_root() { [[ "${EUID:-$(id -u)}" -eq 0 ]] || { echo "Run with sudo"; exit 1; }; }

profile_burst() {
  case "${1:-normal}" in
    normal) echo "512k" ;;
    light) echo "768k" ;;
    desync) echo "2m" ;;
    kick) echo "4m" ;;
    large) echo "2m" ;;
    max) echo "4m" ;;
    *) echo "512k" ;;
  esac
}

ring_scale() {
  case "${1:-normal}" in
    normal) echo "0" ;;
    light) echo "40" ;;
    desync) echo "75" ;;
    kick) echo "100" ;;
    large) echo "75" ;;
    max) echo "100" ;;
    *) echo "0" ;;
  esac
}

write_env() {
  local profile="$1"
  local burst
  burst="$(profile_burst "$profile")"
  cat >"$ENV_FILE" <<EOF
# Generated by gaming-buffer-tune.sh — read by gaming-bandwidth-qos.sh
XBOX_TC_BURST=${burst}
XBOX_BUFFER_PROFILE=${profile}
EOF
}

apply_rings() {
  local scale_pct="$1"
  [[ "$scale_pct" -gt 0 ]] || return 0
  for iface in $PHYS_IFACES; do
    [[ -d "/sys/class/net/$iface" ]] || continue
    local max_rx max_tx target_rx target_tx cur_rx cur_tx
    max_rx=$(ethtool -g "$iface" 2>/dev/null | awk '/Pre-set maximums:/{f=1;next} f&&/RX:/{print $2; exit}') || true
    max_tx=$(ethtool -g "$iface" 2>/dev/null | awk '/Pre-set maximums:/{f=1;next} f&&/TX:/{print $2; exit}') || true
    cur_rx=$(ethtool -g "$iface" 2>/dev/null | awk '/Current hardware settings:/{f=1;next} f&&/RX:/{print $2; exit}') || true
    cur_tx=$(ethtool -g "$iface" 2>/dev/null | awk '/Current hardware settings:/{f=1;next} f&&/TX:/{print $2; exit}') || true
    [[ -n "$max_rx" && -n "$max_tx" ]] || continue
    target_rx=$(( max_rx * scale_pct / 100 ))
    target_tx=$(( max_tx * scale_pct / 100 ))
    [[ "$target_rx" -lt 256 ]] && target_rx=256
    [[ "$target_tx" -lt 256 ]] && target_tx=256
    if [[ "$cur_rx" != "$target_rx" || "$cur_tx" != "$target_tx" ]]; then
      ethtool -G "$iface" rx "$target_rx" tx "$target_tx" 2>/dev/null && \
        log "NIC $iface rings rx=$target_rx tx=$target_tx (${scale_pct}% of max)" || \
        log "NIC $iface ring change skipped (driver may be fixed)"
    fi
  done
}

restore_rings() {
  [[ -f "$RING_STATE" ]] || return 0
  python3 - "$RING_STATE" <<'PY'
import json
import subprocess
import sys

try:
    with open(sys.argv[1], encoding="utf-8") as f:
        state = json.load(f)
except (FileNotFoundError, json.JSONDecodeError):
    sys.exit(0)
for iface, rings in (state.get("rings") or {}).items():
    rx = rings.get("rx")
    tx = rings.get("tx")
    if rx is None or tx is None:
        continue
    subprocess.run(["ethtool", "-G", iface, "rx", str(rx), "tx", str(tx)], check=False)
    print(f"restored {iface} rx={rx} tx={tx}")
PY
}

backup_rings() {
  python3 - "$RING_STATE" "$PHYS_IFACES" <<'PY'
import json
import subprocess
import sys

state_path, ifaces = sys.argv[1], sys.argv[2].split()
rings = {}
for iface in ifaces:
    out = subprocess.run(["ethtool", "-g", iface], capture_output=True, text=True, check=False).stdout
    if not out:
        continue
    cur = {}
    section = None
    for line in out.splitlines():
        line = line.strip()
        if line.startswith("Current hardware settings"):
            section = "current"
            continue
        if section == "current" and ":" in line:
            k, v = [x.strip() for x in line.split(":", 1)]
            if v.isdigit():
                cur[k.lower()] = int(v)
    if cur:
        rings[iface] = {"rx": cur.get("rx"), "tx": cur.get("tx")}
with open(state_path, "w", encoding="utf-8") as f:
    json.dump({"rings": rings}, f, indent=2)
PY
}

apply_sysctl() {
  local profile="$1"
  local backlog=1000
  case "$profile" in
    light|normal) backlog=1500 ;;
    desync|large) backlog=3000 ;;
    kick|max) backlog=5000 ;;
  esac
  sysctl -w "net.core.netdev_max_backlog=${backlog}" >/dev/null 2>&1 || true
  if [[ "$profile" == "max" || "$profile" == "kick" ]]; then
    sysctl -w net.core.rmem_max=16777216 >/dev/null 2>&1 || true
    sysctl -w net.core.wmem_max=16777216 >/dev/null 2>&1 || true
  fi
}

cmd_apply() {
  need_root
  local profile="${1:-large}"
  require_xbox_ip
  backup_rings
  write_env "$profile"
  apply_rings "$(ring_scale "$profile")"
  apply_sysctl "$profile"
  {
    echo "profile=${profile}"
    echo "burst=$(profile_burst "$profile")"
    echo "xbox_ip=${XBOX_IP}"
    echo "updated=$(date -Is)"
  } >"$STATE"
  # Re-apply bandwidth caps so new burst takes effect on existing tc filters.
  if [[ -x "${TOOLS_DIR}/gaming-bandwidth-qos.sh" ]]; then
    if [[ -f "${TOOLS_DIR}/.bandwidth-qos.state" ]]; then
      # shellcheck disable=SC1090
      source "${TOOLS_DIR}/.bandwidth-qos.state" || true
      if [[ "${mode:-}" == "static" ]]; then
        bash "${TOOLS_DIR}/gaming-bandwidth-qos.sh" static "${upload_mbps:-10}" "${download_mbps:-50}" || true
      fi
    fi
  fi
  log "APPLIED profile=${profile} burst=$(profile_burst "$profile") for Xbox ${XBOX_IP}"
}

cmd_off() {
  need_root
  restore_rings
  rm -f "$ENV_FILE" "$STATE" "$RING_STATE"
  sysctl -w net.core.netdev_max_backlog=1000 >/dev/null 2>&1 || true
  log "OFF — Xbox buffer profile cleared, NIC rings restored where possible"
}

cmd_status() {
  [[ -f "$ENV_FILE" ]] && cat "$ENV_FILE" || echo "profile=inactive"
  [[ -f "$STATE" ]] && echo "---" && cat "$STATE"
  for iface in $PHYS_IFACES; do
    [[ -d "/sys/class/net/$iface" ]] || continue
    ethtool -g "$iface" 2>/dev/null | awk -v i="$iface" '/Current hardware settings:/{f=1;next} f&&/^(RX|TX):/{print i, $0}' || true
  done
  sysctl net.core.netdev_max_backlog net.core.rmem_max net.core.wmem_max 2>/dev/null || true
}

case "${1:-status}" in
  apply) shift; cmd_apply "${1:-large}" ;;
  off) cmd_off ;;
  status) cmd_status ;;
  *) echo "Usage: $0 {status|apply normal|light|desync|kick|large|max|off}"; exit 2 ;;
esac
